Script started on 廿十七年三月十三日 (週一) 十三時十分52秒
]0;isabeltseng@isabeltseng-USB: ~/Desktop/lab1[01;32misabeltseng@isabeltseng-USB[00m:[01;34m~/Desktop/lab1[00m$ g==[K[K++ -o count count.cpp
]0;isabeltseng@isabeltseng-USB: ~/Desktop/lab1[01;32misabeltseng@isabeltseng-USB[00m:[01;34m~/Desktop/lab1[00m$ ./count
22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1
]0;isabeltseng@isabeltseng-USB: ~/Desktop/lab1[01;32misabeltseng@isabeltseng-USB[00m:[01;34m~/Desktop/lab1[00m$ exit

Script done on 廿十七年三月十三日 (週一) 十三時十一分卅一秒
